### ISSUE TITLE
How to use this library in production?

### ISSUE THREAD

**Issue by stevepopovich** [m-lab/ndt7-client-android#14]
👋🏼  At my company, we are looking for a native solution to do on-device upload speed tests. I stumbled upon this repo from the better SEO-optimized iOS client. This seems like a great solution but it doesn't seem like it is published anywhere (Maven) and I don't see it advertised anywhere on the mLab website.

Is there a way to use this library on Android (apart from forking/copying the code)? Is it ready for production? Is it actually free? Are there limits to how many upload tests you can run?

Thanks!

**Comment by meggamind** [comment]
This is supported officially by mLab. I can work on publishing it to Maven in a week. So that should make it easier to use. It is ready for production.

**Comment by stevepopovich** [comment]
Wow that would be great! Thanks!

**Comment by stevepopovich** [comment]
I have also found the rest of my answers in https://www.measurementlab.net/develop/ if anyone else stumbles upon this.

**Comment by laiyi-ohlsen** [comment]
Hi @stevepopovich, glad you were able to find the answers you need and @meggamind for your response! To clarify, this repo is not officially supported by the M-Lab core contribution team but we will always do our best to facilitate and review contributions or questions. @stevepopovich if your questions are resolved for now, I'll go ahead and close this issue.

**Comment by stevepopovich** [comment]
That's fine, thanks for following up. Are there any plans to make this repo available via Maven?

**Comment by meggamind** [comment]
I have created a ticket with sonatype, it should be published by the end of this week
